#18 Write a program to input eight numbers from the user and display all the unique numbers (once).
s = set() 
num_1 = int(input("Enter the number:"))
s.add(num_1)
num_2 = int(input("Enter the number:"))
s.add(num_2)
num_3 = int(input("Enter the number:"))
s.add(num_3)
num_4 = int(input("Enter the number:"))
s.add(num_4)
num_5 = int(input("Enter the number:"))
s.add(num_5)
num_6 = int(input("Enter the number:"))
s.add(num_6)
num_7 = int(input("Enter the number:"))
s.add(num_7)
num_8 = int(input("Enter the number:"))
s.add(num_8)

print(f"The unique numbers are: {s}")

